// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PATH/NetModel.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace SerAndDeSer.UseGoogleProtobuf {

  /// <summary>Holder for reflection information generated from PATH/NetModel.proto</summary>
  public static partial class NetModelReflection {

    #region Descriptor
    /// <summary>File descriptor for PATH/NetModel.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NetModelReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNQQVRIL05ldE1vZGVsLnByb3RvEh1TZXJBbmREZVNlci5Vc2VHb29nbGVQ",
            "cm90b2J1ZiIsCgtDb25uZWN0VXNlchIKCgJJZBgBIAEoAxIRCglBdXRoVG9r",
            "ZW4YAiABKAki0AEKCk5ldFJlcXVlc3QSPAoIQ29ublVzZXIYASABKAsyKi5T",
            "ZXJBbmREZVNlci5Vc2VHb29nbGVQcm90b2J1Zi5Db25uZWN0VXNlchIOCgZB",
            "Y3Rpb24YAiABKAkSRQoGUGFyYW1zGAMgAygLMjUuU2VyQW5kRGVTZXIuVXNl",
            "R29vZ2xlUHJvdG9idWYuTmV0UmVxdWVzdC5QYXJhbXNFbnRyeRotCgtQYXJh",
            "bXNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIi8KC05l",
            "dFJlc3BvbnNlEg8KB1N1Y2Nlc3MYASABKAgSDwoHTWVzc2FnZRgCIAEoCSKq",
            "AQoHUGJUZXN0MRIQCghNeURvdWJsZRgBIAEoARIPCgdNeUZsb2F0GAIgASgC",
            "Eg8KB015SW50MzIYAyABKAUSEAoITXlVaW50MzIYBCABKA0SEAoITXlVaW50",
            "NjQYBSABKAQSDgoGTXlCb29sGAYgASgIEhAKCE15U3RyaW5nGAcgASgJEg8K",
            "B015Qnl0ZXMYCCABKAwSFAoMTXlTdHJpbmdMaXN0GAkgAygJYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::SerAndDeSer.UseGoogleProtobuf.ConnectUser), global::SerAndDeSer.UseGoogleProtobuf.ConnectUser.Parser, new[]{ "Id", "AuthToken" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SerAndDeSer.UseGoogleProtobuf.NetRequest), global::SerAndDeSer.UseGoogleProtobuf.NetRequest.Parser, new[]{ "ConnUser", "Action", "Params" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::SerAndDeSer.UseGoogleProtobuf.NetResponse), global::SerAndDeSer.UseGoogleProtobuf.NetResponse.Parser, new[]{ "Success", "Message" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::SerAndDeSer.UseGoogleProtobuf.PbTest1), global::SerAndDeSer.UseGoogleProtobuf.PbTest1.Parser, new[]{ "MyDouble", "MyFloat", "MyInt32", "MyUint32", "MyUint64", "MyBool", "MyString", "MyBytes", "MyStringList" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ConnectUser : pb::IMessage<ConnectUser> {
    private static readonly pb::MessageParser<ConnectUser> _parser = new pb::MessageParser<ConnectUser>(() => new ConnectUser());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ConnectUser> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SerAndDeSer.UseGoogleProtobuf.NetModelReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectUser() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectUser(ConnectUser other) : this() {
      id_ = other.id_;
      authToken_ = other.authToken_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ConnectUser Clone() {
      return new ConnectUser(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    /// <summary>
    ///用户ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "AuthToken" field.</summary>
    public const int AuthTokenFieldNumber = 2;
    private string authToken_ = "";
    /// <summary>
    ///链接授权信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AuthToken {
      get { return authToken_; }
      set {
        authToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ConnectUser);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ConnectUser other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (AuthToken != other.AuthToken) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (AuthToken.Length != 0) hash ^= AuthToken.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (AuthToken.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AuthToken);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (AuthToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AuthToken);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ConnectUser other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.AuthToken.Length != 0) {
        AuthToken = other.AuthToken;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            AuthToken = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///test url :   /test
  /// </summary>
  public sealed partial class NetRequest : pb::IMessage<NetRequest> {
    private static readonly pb::MessageParser<NetRequest> _parser = new pb::MessageParser<NetRequest>(() => new NetRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NetRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SerAndDeSer.UseGoogleProtobuf.NetModelReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetRequest(NetRequest other) : this() {
      ConnUser = other.connUser_ != null ? other.ConnUser.Clone() : null;
      action_ = other.action_;
      params_ = other.params_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetRequest Clone() {
      return new NetRequest(this);
    }

    /// <summary>Field number for the "ConnUser" field.</summary>
    public const int ConnUserFieldNumber = 1;
    private global::SerAndDeSer.UseGoogleProtobuf.ConnectUser connUser_;
    /// <summary>
    ///链接用户信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::SerAndDeSer.UseGoogleProtobuf.ConnectUser ConnUser {
      get { return connUser_; }
      set {
        connUser_ = value;
      }
    }

    /// <summary>Field number for the "Action" field.</summary>
    public const int ActionFieldNumber = 2;
    private string action_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Action {
      get { return action_; }
      set {
        action_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Params" field.</summary>
    public const int ParamsFieldNumber = 3;
    private static readonly pbc::MapField<string, string>.Codec _map_params_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForString(18), 26);
    private readonly pbc::MapField<string, string> params_ = new pbc::MapField<string, string>();
    /// <summary>
    ///请求参数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> Params {
      get { return params_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NetRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NetRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ConnUser, other.ConnUser)) return false;
      if (Action != other.Action) return false;
      if (!Params.Equals(other.Params)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (connUser_ != null) hash ^= ConnUser.GetHashCode();
      if (Action.Length != 0) hash ^= Action.GetHashCode();
      hash ^= Params.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (connUser_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ConnUser);
      }
      if (Action.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Action);
      }
      params_.WriteTo(output, _map_params_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (connUser_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ConnUser);
      }
      if (Action.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Action);
      }
      size += params_.CalculateSize(_map_params_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NetRequest other) {
      if (other == null) {
        return;
      }
      if (other.connUser_ != null) {
        if (connUser_ == null) {
          connUser_ = new global::SerAndDeSer.UseGoogleProtobuf.ConnectUser();
        }
        ConnUser.MergeFrom(other.ConnUser);
      }
      if (other.Action.Length != 0) {
        Action = other.Action;
      }
      params_.Add(other.params_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (connUser_ == null) {
              connUser_ = new global::SerAndDeSer.UseGoogleProtobuf.ConnectUser();
            }
            input.ReadMessage(connUser_);
            break;
          }
          case 18: {
            Action = input.ReadString();
            break;
          }
          case 26: {
            params_.AddEntriesFrom(input, _map_params_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///定义一个类，用于响应客户端请求
  /// </summary>
  public sealed partial class NetResponse : pb::IMessage<NetResponse> {
    private static readonly pb::MessageParser<NetResponse> _parser = new pb::MessageParser<NetResponse>(() => new NetResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<NetResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SerAndDeSer.UseGoogleProtobuf.NetModelReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetResponse(NetResponse other) : this() {
      success_ = other.success_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public NetResponse Clone() {
      return new NetResponse(this);
    }

    /// <summary>Field number for the "Success" field.</summary>
    public const int SuccessFieldNumber = 1;
    private bool success_;
    /// <summary>
    ///成功指示
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    /// <summary>Field number for the "Message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    /// <summary>
    ///结果描述信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as NetResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(NetResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Success != other.Success) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Success != false) hash ^= Success.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Success != false) {
        size += 1 + 1;
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(NetResponse other) {
      if (other == null) {
        return;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///测试测试
  /// </summary>
  public sealed partial class PbTest1 : pb::IMessage<PbTest1> {
    private static readonly pb::MessageParser<PbTest1> _parser = new pb::MessageParser<PbTest1>(() => new PbTest1());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PbTest1> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::SerAndDeSer.UseGoogleProtobuf.NetModelReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PbTest1() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PbTest1(PbTest1 other) : this() {
      myDouble_ = other.myDouble_;
      myFloat_ = other.myFloat_;
      myInt32_ = other.myInt32_;
      myUint32_ = other.myUint32_;
      myUint64_ = other.myUint64_;
      myBool_ = other.myBool_;
      myString_ = other.myString_;
      myBytes_ = other.myBytes_;
      myStringList_ = other.myStringList_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PbTest1 Clone() {
      return new PbTest1(this);
    }

    /// <summary>Field number for the "MyDouble" field.</summary>
    public const int MyDoubleFieldNumber = 1;
    private double myDouble_;
    /// <summary>
    ///double数据类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double MyDouble {
      get { return myDouble_; }
      set {
        myDouble_ = value;
      }
    }

    /// <summary>Field number for the "MyFloat" field.</summary>
    public const int MyFloatFieldNumber = 2;
    private float myFloat_;
    /// <summary>
    ///是的爽肤水
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float MyFloat {
      get { return myFloat_; }
      set {
        myFloat_ = value;
      }
    }

    /// <summary>Field number for the "MyInt32" field.</summary>
    public const int MyInt32FieldNumber = 3;
    private int myInt32_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int MyInt32 {
      get { return myInt32_; }
      set {
        myInt32_ = value;
      }
    }

    /// <summary>Field number for the "MyUint32" field.</summary>
    public const int MyUint32FieldNumber = 4;
    private uint myUint32_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint MyUint32 {
      get { return myUint32_; }
      set {
        myUint32_ = value;
      }
    }

    /// <summary>Field number for the "MyUint64" field.</summary>
    public const int MyUint64FieldNumber = 5;
    private ulong myUint64_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong MyUint64 {
      get { return myUint64_; }
      set {
        myUint64_ = value;
      }
    }

    /// <summary>Field number for the "MyBool" field.</summary>
    public const int MyBoolFieldNumber = 6;
    private bool myBool_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool MyBool {
      get { return myBool_; }
      set {
        myBool_ = value;
      }
    }

    /// <summary>Field number for the "MyString" field.</summary>
    public const int MyStringFieldNumber = 7;
    private string myString_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MyString {
      get { return myString_; }
      set {
        myString_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "MyBytes" field.</summary>
    public const int MyBytesFieldNumber = 8;
    private pb::ByteString myBytes_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString MyBytes {
      get { return myBytes_; }
      set {
        myBytes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "MyStringList" field.</summary>
    public const int MyStringListFieldNumber = 9;
    private static readonly pb::FieldCodec<string> _repeated_myStringList_codec
        = pb::FieldCodec.ForString(74);
    private readonly pbc::RepeatedField<string> myStringList_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> MyStringList {
      get { return myStringList_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PbTest1);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PbTest1 other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(MyDouble, other.MyDouble)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MyFloat, other.MyFloat)) return false;
      if (MyInt32 != other.MyInt32) return false;
      if (MyUint32 != other.MyUint32) return false;
      if (MyUint64 != other.MyUint64) return false;
      if (MyBool != other.MyBool) return false;
      if (MyString != other.MyString) return false;
      if (MyBytes != other.MyBytes) return false;
      if(!myStringList_.Equals(other.myStringList_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MyDouble != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(MyDouble);
      if (MyFloat != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MyFloat);
      if (MyInt32 != 0) hash ^= MyInt32.GetHashCode();
      if (MyUint32 != 0) hash ^= MyUint32.GetHashCode();
      if (MyUint64 != 0UL) hash ^= MyUint64.GetHashCode();
      if (MyBool != false) hash ^= MyBool.GetHashCode();
      if (MyString.Length != 0) hash ^= MyString.GetHashCode();
      if (MyBytes.Length != 0) hash ^= MyBytes.GetHashCode();
      hash ^= myStringList_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MyDouble != 0D) {
        output.WriteRawTag(9);
        output.WriteDouble(MyDouble);
      }
      if (MyFloat != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(MyFloat);
      }
      if (MyInt32 != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(MyInt32);
      }
      if (MyUint32 != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(MyUint32);
      }
      if (MyUint64 != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(MyUint64);
      }
      if (MyBool != false) {
        output.WriteRawTag(48);
        output.WriteBool(MyBool);
      }
      if (MyString.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(MyString);
      }
      if (MyBytes.Length != 0) {
        output.WriteRawTag(66);
        output.WriteBytes(MyBytes);
      }
      myStringList_.WriteTo(output, _repeated_myStringList_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MyDouble != 0D) {
        size += 1 + 8;
      }
      if (MyFloat != 0F) {
        size += 1 + 4;
      }
      if (MyInt32 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MyInt32);
      }
      if (MyUint32 != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MyUint32);
      }
      if (MyUint64 != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(MyUint64);
      }
      if (MyBool != false) {
        size += 1 + 1;
      }
      if (MyString.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MyString);
      }
      if (MyBytes.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(MyBytes);
      }
      size += myStringList_.CalculateSize(_repeated_myStringList_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PbTest1 other) {
      if (other == null) {
        return;
      }
      if (other.MyDouble != 0D) {
        MyDouble = other.MyDouble;
      }
      if (other.MyFloat != 0F) {
        MyFloat = other.MyFloat;
      }
      if (other.MyInt32 != 0) {
        MyInt32 = other.MyInt32;
      }
      if (other.MyUint32 != 0) {
        MyUint32 = other.MyUint32;
      }
      if (other.MyUint64 != 0UL) {
        MyUint64 = other.MyUint64;
      }
      if (other.MyBool != false) {
        MyBool = other.MyBool;
      }
      if (other.MyString.Length != 0) {
        MyString = other.MyString;
      }
      if (other.MyBytes.Length != 0) {
        MyBytes = other.MyBytes;
      }
      myStringList_.Add(other.myStringList_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 9: {
            MyDouble = input.ReadDouble();
            break;
          }
          case 21: {
            MyFloat = input.ReadFloat();
            break;
          }
          case 24: {
            MyInt32 = input.ReadInt32();
            break;
          }
          case 32: {
            MyUint32 = input.ReadUInt32();
            break;
          }
          case 40: {
            MyUint64 = input.ReadUInt64();
            break;
          }
          case 48: {
            MyBool = input.ReadBool();
            break;
          }
          case 58: {
            MyString = input.ReadString();
            break;
          }
          case 66: {
            MyBytes = input.ReadBytes();
            break;
          }
          case 74: {
            myStringList_.AddEntriesFrom(input, _repeated_myStringList_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
