// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PATH/Test/SysEnumeration.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GrpcTest.Services.Enumeration {

  /// <summary>Holder for reflection information generated from PATH/Test/SysEnumeration.proto</summary>
  public static partial class SysEnumerationReflection {

    #region Descriptor
    /// <summary>File descriptor for PATH/Test/SysEnumeration.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SysEnumerationReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch5QQVRIL1Rlc3QvU3lzRW51bWVyYXRpb24ucHJvdG8SHUdycGNUZXN0LlNl",
            "cnZpY2VzLkVudW1lcmF0aW9uKtoCCgpFcnJvckNvZGVzEgsKB1N1Y2Nlc3MQ",
            "ABIRCg1TaWduVmFsaWRGYWlsEAESFAoQUmVxRGF0YVZhbGlkRmFpbBACEhEK",
            "DU9wZXJhdGlvbkZhaWwQAxIVChFJbnZhbGlkTG9naW5Ub2tlbhAEEhYKElBh",
            "c3N3b3JkSGFzQmVlblNldBAFEgwKCFN5c0Vycm9yEAYSDwoLVXNlck9wdEZh",
            "aWwQBxIMCghOb3RGb3VuZBAIEhcKE1RpbWVzdGFtcE91dE9mUmFuZ2UQCRIV",
            "ChFQYXNzd29yZE5vQmVlblNldBAKEhQKEEludmFsaWRBdXRoU3RhdGUQCxIO",
            "CgpCaW5kV3hGYWlsEAwSDQoJQ2ZzVW5iaW5kEA0SCwoHQXBpRmFpbBAOEhAK",
            "DFVuYXV0aG9yaXplZBAPEg0KCVBhcmFtc0VychAQEhQKEFByZWNvbmRpdGlv",
            "bkZhaWwQESpFCg1NYXJpdGFsU3RhdGVzEg0KCVVubWFycmllZBAAEgsKB01h",
            "cnJpZWQQARIYChRVbmtub3duX01hcml0YWxTdGF0ZRACKqwBCgtDbGllbnRU",
            "eXBlcxIGCgJQQxAAEgcKA2lPcxABEgsKB0FuZHJvaWQQAhIPCgtTdG9yZVNl",
            "cnZlchADEgwKCENhbGxfaU9TEAQSEAoMQ2FsbF9BbmRyb2lkEAUSCwoHQ2Fs",
            "bF9QQxAGEgYKAkFJEAcSBwoDV2ViEAgSDgoKQnVzaVNlcnZlchAKEg0KCUNh",
            "bGwyX2lPUxBlEhEKDUNhbGwyX0FuZHJvaWQQZipxCghTZXJ2aWNlcxIQCgxV",
            "bnNldFNlcnZpY2UQABIHCgNDZnMQARIPCgtDZnNDdXN0b21lchACEg0KCVBh",
            "eUNlbnRlchADEg0KCVRoaXJkcGFydBAEEg4KClByb2Zlc3NvclgQBRILCgdD",
            "YWxsRmVlEAZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GrpcTest.Services.Enumeration.ErrorCodes), typeof(global::GrpcTest.Services.Enumeration.MaritalStates), typeof(global::GrpcTest.Services.Enumeration.ClientTypes), typeof(global::GrpcTest.Services.Enumeration.Services), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///错误编号
  /// </summary>
  public enum ErrorCodes {
    /// <summary>
    ///成功
    /// </summary>
    [pbr::OriginalName("Success")] Success = 0,
    /// <summary>
    ///签名验证失败
    /// </summary>
    [pbr::OriginalName("SignValidFail")] SignValidFail = 1,
    /// <summary>
    ///请求数据验证失败
    /// </summary>
    [pbr::OriginalName("ReqDataValidFail")] ReqDataValidFail = 2,
    /// <summary>
    ///（服务端）操作失败
    /// </summary>
    [pbr::OriginalName("OperationFail")] OperationFail = 3,
    /// <summary>
    ///失效的登录令牌
    /// </summary>
    [pbr::OriginalName("InvalidLoginToken")] InvalidLoginToken = 4,
    /// <summary>
    ///密码已被设置，不能重新设置
    /// </summary>
    [pbr::OriginalName("PasswordHasBeenSet")] PasswordHasBeenSet = 5,
    /// <summary>
    /// 系统异常
    /// </summary>
    [pbr::OriginalName("SysError")] SysError = 6,
    /// <summary>
    ///用户操作失败
    /// </summary>
    [pbr::OriginalName("UserOptFail")] UserOptFail = 7,
    /// <summary>
    ///未找到
    /// </summary>
    [pbr::OriginalName("NotFound")] NotFound = 8,
    /// <summary>
    ///时间戳超出范围
    /// </summary>
    [pbr::OriginalName("TimestampOutOfRange")] TimestampOutOfRange = 9,
    /// <summary>
    ///密码尚未设定，不能修改
    /// </summary>
    [pbr::OriginalName("PasswordNoBeenSet")] PasswordNoBeenSet = 10,
    /// <summary>
    ///非法的账户审核状态
    /// </summary>
    [pbr::OriginalName("InvalidAuthState")] InvalidAuthState = 11,
    /// <summary>
    ///微信绑定失败
    /// </summary>
    [pbr::OriginalName("BindWxFail")] BindWxFail = 12,
    /// <summary>
    ///CFS账号未绑定
    /// </summary>
    [pbr::OriginalName("CfsUnbind")] CfsUnbind = 13,
    /// <summary>
    ///接口返回失败
    /// </summary>
    [pbr::OriginalName("ApiFail")] ApiFail = 14,
    /// <summary>
    ///权限检查未通过
    /// </summary>
    [pbr::OriginalName("Unauthorized")] Unauthorized = 15,
    /// <summary>
    ///传参错误
    /// </summary>
    [pbr::OriginalName("ParamsErr")] ParamsErr = 16,
    /// <summary>
    ///前提条件失败
    /// </summary>
    [pbr::OriginalName("PreconditionFail")] PreconditionFail = 17,
  }

  /// <summary>
  ///婚姻状况枚举
  /// </summary>
  public enum MaritalStates {
    /// <summary>
    ///未婚
    /// </summary>
    [pbr::OriginalName("Unmarried")] Unmarried = 0,
    /// <summary>
    ///已婚
    /// </summary>
    [pbr::OriginalName("Married")] Married = 1,
    /// <summary>
    ///未知
    /// </summary>
    [pbr::OriginalName("Unknown_MaritalState")] UnknownMaritalState = 2,
  }

  /// <summary>
  ///客户端类型，此enum应与CFS的DuiContract.DataModel.ClientType保持一致
  /// </summary>
  public enum ClientTypes {
    /// <summary>
    ///桌面电脑
    /// </summary>
    [pbr::OriginalName("PC")] Pc = 0,
    /// <summary>
    ///iOS
    /// </summary>
    [pbr::OriginalName("iOs")] IOs = 1,
    /// <summary>
    ///Android
    /// </summary>
    [pbr::OriginalName("Android")] Android = 2,
    /// <summary>
    ///门店
    /// </summary>
    [pbr::OriginalName("StoreServer")] StoreServer = 3,
    /// <summary>
    ///软电话iOS
    /// </summary>
    [pbr::OriginalName("Call_iOS")] CallIOs = 4,
    /// <summary>
    ///软电话android
    /// </summary>
    [pbr::OriginalName("Call_Android")] CallAndroid = 5,
    /// <summary>
    ///软电话桌面电脑
    /// </summary>
    [pbr::OriginalName("Call_PC")] CallPc = 6,
    /// <summary>
    ///AI服务
    /// </summary>
    [pbr::OriginalName("AI")] Ai = 7,
    /// <summary>
    ///网页
    /// </summary>
    [pbr::OriginalName("Web")] Web = 8,
    /// <summary>
    ///业务系统
    /// </summary>
    [pbr::OriginalName("BusiServer")] BusiServer = 10,
    /// <summary>
    ///软电话iOS2
    /// </summary>
    [pbr::OriginalName("Call2_iOS")] Call2IOs = 101,
    /// <summary>
    ///软电话Android2
    /// </summary>
    [pbr::OriginalName("Call2_Android")] Call2Android = 102,
  }

  /// <summary>
  ///服务
  /// </summary>
  public enum Services {
    /// <summary>
    ///未指定
    /// </summary>
    [pbr::OriginalName("UnsetService")] UnsetService = 0,
    /// <summary>
    ///CFS后台服务
    /// </summary>
    [pbr::OriginalName("Cfs")] Cfs = 1,
    /// <summary>
    ///顾客端服务
    /// </summary>
    [pbr::OriginalName("CfsCustomer")] CfsCustomer = 2,
    /// <summary>
    ///支付中心服务
    /// </summary>
    [pbr::OriginalName("PayCenter")] PayCenter = 3,
    /// <summary>
    ///第三方服务（Xxjr.Thirdpart）
    /// </summary>
    [pbr::OriginalName("Thirdpart")] Thirdpart = 4,
    /// <summary>
    ///服务管理服务
    /// </summary>
    [pbr::OriginalName("ProfessorX")] ProfessorX = 5,
    /// <summary>
    ///话费
    /// </summary>
    [pbr::OriginalName("CallFee")] CallFee = 6,
  }

  #endregion

}

#endregion Designer generated code
