// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PATH/Test/GrpcTestService.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GrpcTest.Service.GrpcSvc {

  /// <summary>Holder for reflection information generated from PATH/Test/GrpcTestService.proto</summary>
  public static partial class GrpcTestServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for PATH/Test/GrpcTestService.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GrpcTestServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9QQVRIL1Rlc3QvR3JwY1Rlc3RTZXJ2aWNlLnByb3RvEhhHcnBjVGVzdC5T",
            "ZXJ2aWNlLkdycGNTdmMaGFRlc3QvR3JwY1Rlc3RNb2RlbC5wcm90bxoYVGVz",
            "dC9SZXNwb25zZU1vZGVsLnByb3RvMpEDCgdUZXN0U3ZjEl4KCVJlZ2lzdGVy",
            "MRIjLkdycGNUZXN0LlNlcnZpY2UuTW9kZWxzLlJlZ2lzdGVyUnEaKi5HcnBj",
            "LlNlcnZpY2UuTW9kZWwuRXhlY3V0ZVJlc3VsdC5QYk1zZ1JldCIAEmAKCVJl",
            "Z2lzdGVyMhIjLkdycGNUZXN0LlNlcnZpY2UuTW9kZWxzLlJlZ2lzdGVyUnEa",
            "Ki5HcnBjLlNlcnZpY2UuTW9kZWwuRXhlY3V0ZVJlc3VsdC5QYk1zZ1JldCIA",
            "MAESYAoJUmVnaXN0ZXIzEiMuR3JwY1Rlc3QuU2VydmljZS5Nb2RlbHMuUmVn",
            "aXN0ZXJScRoqLkdycGMuU2VydmljZS5Nb2RlbC5FeGVjdXRlUmVzdWx0LlBi",
            "TXNnUmV0IgAoARJiCglSZWdpc3RlcjQSIy5HcnBjVGVzdC5TZXJ2aWNlLk1v",
            "ZGVscy5SZWdpc3RlclJxGiouR3JwYy5TZXJ2aWNlLk1vZGVsLkV4ZWN1dGVS",
            "ZXN1bHQuUGJNc2dSZXQiACgBMAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::GrpcTest.Service.Models.GrpcTestModelReflection.Descriptor, global::Grpc.Service.Model.ExecuteResult.ResponseModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
